name: amd64 Linux

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  # Building using the github runner environement directly.
  linux:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         build: [
           ["Unix Makefiles", "Release"],
           ["Ninja", "Release"],
           ["Ninja Multi-Config", "Release"]
         ]
       fail-fast: false
    env:
      GENERATOR: ${{ matrix.build[0] }}
      BUILD_TYPE: ${{ matrix.build[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Ninja
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "$GENERATOR" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_INSTALL_PREFIX=install
    - name: Build
      run: cmake --build build --config "$BUILD_TYPE" --target all -v
    - name: Test
      run: cmake --build build --config "$BUILD_TYPE" --target test -v
    - name: Install
      run: cmake --build build --config "$BUILD_TYPE" --target install -v
